name: Build AlaskarFin

on:
  push:
    paths:
      - alaskarfin/version.txt

jobs:
  build-alaskarfin:
    runs-on: host

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push the Docker image
      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: alaskarfin # Path to the build context
          file: alaskarfin/Dockerfile # Path to the Dockerfile
          push: true # Push the image to Docker Hub
          tags: |
            nomadics/alaskarfin:latest

      # Step 5: Log in to Forgejo
      - name: Log in to Forgejo
        uses: docker/login-action@v3
        with:
          registry: git.askar.tv
          username: nomad
          password: ${{ secrets.FORGEJO_TOKEN }}

      # Step 4: Build and push the Docker image
      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: alaskarfin # Path to the build context
          file: alaskarfin/Dockerfile # Path to the Dockerfile
          push: true # Push the image to Docker Hub
          tags: |
            git.askar.tv/nomad/alaskarfin:latest
