name: Build AlaskarFin

on:
  push:
    paths:
      - alaskarfin/version.txt

jobs:
  build-alaskarfin:
    runs-on: host

    steps:
      - name: Add host entry
        run: |
          echo "192.168.0.200 git.askar.tv" | sudo tee -a /etc/hosts
          getent hosts git.askar.tv

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to Forgejo
        uses: docker/login-action@v3
        with:
          registry: git.askar.tv
          username: nomad
          password: ${{ secrets.FORGEJO_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: alaskarfin
          file: alaskarfin/Dockerfile
          push: true
          tags: |
            nomadics/alaskarfin:latest
            git.askar.tv/nomad/alaskarfin:latest
